# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='has_paid',
            field=models.BooleanField(default=False, help_text='Hvis sann har den påmeldte betalt for billett.', verbose_name='Har betalt'),
        ),
    ]
