# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180105_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Unik id som ingen kan gjette seg til..', unique=True,
                                   verbose_name='unik billett id'),
        ),
    ]
