# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180105_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='Om personen har sjekket inn på arrangementet.', verbose_name='Sjekket inn'),
        ),
    ]
