# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventregistration_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='has_received_ticket',
            field=models.BooleanField(default=False, help_text='Om billetten har blitt tilsendt brukeren på epost', verbose_name='Har mottatt billett'),
        ),
    ]
