# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventregistration_has_received_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hidden_to_public',
            field=models.BooleanField(default=False, verbose_name='Skjult for gjester'),
        ),
    ]
