# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=80, unique=True, verbose_name='E-post'),
        ),
    ]
