# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171001_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_awaiting_approval',
            field=models.BooleanField(default=True, verbose_name='Avventer godkjenning'),
        ),
    ]
