# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171016_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_users', 'Can view users awaiting checkup for registration'), ('can_change_users', 'Can change user status during checkup for registration'))},
        ),
    ]
