# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20171016_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_verified',
            field=models.BooleanField(default=False, verbose_name='Godkjent konto (e-post er verifisert)'),
        ),
    ]
