# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_account_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_verified',
            field=models.BooleanField(default=False, verbose_name='Verifisert konto (e-post)'),
        ),
    ]
