# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, verbose_name='Allergier'),
        ),
    ]
